export enum UserRole {
  PATIENT = 'PATIENT',
  COUNSELOR = 'COUNSELOR',
  COUNSELOR_ADMIN = 'COUNSELOR_ADMIN',
  PARTNER = 'PARTNER',
  PARTNER_ADMIN = 'PARTNER_ADMIN',
  ADMIN = 'ADMIN',
  EDITOR = 'EDITOR',
}
