export enum VerificationType {
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
  PASSWORD_RESET = 'PASSWORD_RESET',
  ACCOUNT_UNLOCK = 'ACCOUNT_UNLOCK',
  TWO_FACTOR_SETUP = 'TWO_FACTOR_SETUP',
  ACCOUNT_DELETION = 'ACCOUNT_DELETION',
  TWO_FACTOR_AUTH = 'TWO_FACTOR_AUTH',
}
